About this file

Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.

Dataset can be used for Binary Classification sample problems

In [17]:
# !pip install flasgger

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('BankNote_Authentication.csv')

In [3]:
data

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

## checking any missing value

In [4]:
data.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

In [5]:
data.corr()

variance  skewness  curtosis   entropy     class
variance  1.000000  0.264026 -0.380850  0.276817 -0.724843
skewness  0.264026  1.000000 -0.786895 -0.526321 -0.444688
curtosis -0.380850 -0.786895  1.000000  0.318841  0.155883
entropy   0.276817 -0.526321  0.318841  1.000000 -0.023424
class    -0.724843 -0.444688  0.155883 -0.023424  1.000000

 entropy is less correlated with class

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x = data.iloc[:,:-1]

In [8]:
y = data.iloc[:,-1]

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

# Randomforest classifier

In [19]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100, random_state = 20)
rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=20, verbose=0,
                       warm_start=False)

In [20]:
 y_predict = rf.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

0.9933774834437086

In [22]:
accuracy_on_train = rf.score(x_train, y_train)
accuracy_on_test = rf.score(x_test, y_test)
accuracy_on_train, accuracy_on_test

(1.0, 0.9933774834437086)

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_score(rf,x,y,cv=3)

array([0.99344978, 0.99562363, 0.99562363])

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       257
           1       1.00      0.98      0.99       196

    accuracy                           0.99       453
   macro avg       0.99      0.99      0.99       453
weighted avg       0.99      0.99      0.99       453



In [26]:
rf.predict([[2,3,4,1]])

array([0], dtype=int64)

# XGBOOST 

In [23]:
# !pip install xgboost

In [10]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [11]:
y_predi = classifier.predict(x_test)

In [12]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predi)

1.0

In [12]:
from sklearn.metrics import confusion_matrix
Con_mat = confusion_matrix(y_test,y_predi)

In [13]:
accuracy_on_train = classifier.score(x_train, y_train)
accuracy_on_test = classifier.score(x_test, y_test)
accuracy_on_train, accuracy_on_test

(1.0, 1.0)

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(classifier,x,y,cv=3)

array([0.99781659, 0.99343545, 0.99562363])

In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predi))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       257
           1       1.00      1.00      1.00       196

    accuracy                           1.00       453
   macro avg       1.00      1.00      1.00       453
weighted avg       1.00      1.00      1.00       453



In [16]:
classifier.predict([[2, 3,4,1]])

SyntaxError: invalid syntax (<ipython-input-16-9e2d058e2e68>, line 1)

# PICKLE FILE

In [27]:
import pickle
pickle_out = open("trained_model.pkl","wb")
pickle.dump(rf, pickle_out)
pickle_out.close()

In [28]:
import numpy as np

In [29]:
rf.predict([[2,3,4,1]])

array([0], dtype=int64)